# -*- coding: utf-8 -*-
"""Cópia de eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hVTUlJQj9yE9ta3GmlGQ8O53RPFepO4u
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import kagglehub
path = kagglehub.dataset_download("pavansubhasht/ibm-hr-analytics-attrition-dataset")

import os
file_path = os.path.join(path, "WA_Fn-UseC_-HR-Employee-Attrition.csv")
df = pd.read_csv(file_path)
df.head()

df.info()



df.describe()

plt.figure(figsize=(15,5))
sns.histplot(df['Age'],kde=1)

""" # Curva de densidade (kde): a linha suave sobreposta mostra a tendência da distribuição, ajudando a visualizar onde estão as maiores concentrações de valores.

curva parece ter um único pico entre 30 e 40 anos, o que sugere algo próximo de uma distribuição unimodal.


"""

# skew = 0 → distribuição simétrica (normal).
# skew > 0 → cauda à direita (assimétrica positiva).
# skew < 0 → cauda à esquerda (assimétrica negativa).
# kurt = 3 → parecido com normal. Valores maiores indicam caudas mais pesadas.

print(df['Age'].skew())   # mede a assimetria
print(df['Age'].kurt())   # mede a curtose (achatamento)

"""Skew (assimetria) = 0.41 → isso indica uma leve assimetria positiva, ou seja, a cauda da distribuição está um pouco mais alongada para a direita (idades mais altas). Não é um valor muito grande, então a distribuição ainda é relativamente próxima da simétrica.

Kurtosis (curtose) = -0.40 → isso mostra que a distribuição é um pouco mais achatada do que a normal (menos concentrada no centro e com caudas mais leves).

Em resumo:
A distribuição das idadesnão é perfeitamente normal, mas está próxima de uma curva unimodal, Ela tem uma leve tendência para valores mais altos (assimetria positiva) e é um pouco mais achatada do que a normal.
"""

# teste de normalidade
# Esse teste vai te dar uma evidência estatística se os dados seguem ou não uma distribuição normal.

from scipy.stats import shapiro

stat, p = shapiro(df['Age'])
print('Estatística=%.3f, p=%.3f' % (stat, p))

if p > 0.05:
    print("Distribuição parece normal")
else:
    print("Distribuição não é normal")

"""Em resumo:

O p-valor < 0.05 indica que rejeitamos a hipótese nula de normalidade.

Ou seja, a distribuição das idades não segue uma distribuição normal.

Isso confirma o que já vimos no histograma e nas medidas de assimetria/curtose: os dados têm uma forma própria, com pico entre 30–40 anos, mas não se encaixam perfeitamente na curva normal.
"""

# Esse gráfico mostra se os pontos seguem a linha reta da normal.
# Transformações (log, Box-Cox, etc.) se você precisar aproximar a normalidade para análises estatísticas que exigem isso.
# Ou simplesmente aceitar que sua variável "Age" tem uma distribuição própria, o que é comum em dados demográficos.

import scipy.stats as stats

stats.probplot(df['Age'], dist="norm", plot=plt)
plt.show()

"""#Os pontos azuis representam os quantis dos seus dados de idade.
# A linha vermelha é a referência de uma distribuição normal.

O que deu para descobrir sobre a coluna Age:

O histograma mostrou que a maioria dos funcionários está na faixa dos 30–40 anos.

O teste de normalidade (Shapiro-Wilk) e o QQ-plot confirmaram que a distribuição não é normal.

# Isso é esperado em dados de RH, porque a idade dos funcionários geralmente segue padrões organizacionais (contratações, aposentadorias, etc.), e não uma curva normal perfeita.
"""

# total de atrtito
sns.countplot(x='Attrition', data=df)
plt.title("Attrition Distribution")
plt.show()

# MonthlyIncome
# visualização da renda mensal

plt.figure(figsize=(15, 5))

sns.histplot(df['MonthlyIncome'],kde=True)

# Pergunta: Funcionários que saíram da empresa estão concentrados em alguma faixa etária?
# Attrition (rotatividade) vs. Age

sns.histplot(data=df, x="Age", hue="Attrition", multiple="stack", kde=True)

# Pergunta: Certos cargos ou departamentos têm perfis de idade diferentes?
# JobRole / Department vs. Age

plt.figure(figsize=(12,6))
sns.boxplot(data=df, x="JobRole", y="Age")
plt.xticks(rotation=45)

# Pergunta: Como idade se relaciona com tempo de empresa e experiência total?
# YearsAtCompany / TotalWorkingYears vs. Age

sns.scatterplot(data=df, x="Age", y="YearsAtCompany", hue="Attrition")

# Pergunta: Idade influencia satisfação ou desempenho?
# PerformanceRating / JobSatisfaction vs. Age

sns.boxplot(data=df, x="JobSatisfaction", y="Age")
sns.boxplot(data=df, x="PerformanceRating", y="Age")

"""###  JobSatisfaction vs. Age (boxplot)
- Funcionários com diferentes níveis de satisfação têm distribuições de idade relativamente próximas.  
- Não há uma diferença gritante, mas dá para notar que níveis mais altos de satisfação tendem a incluir funcionários um pouco mais velhos.  
- Isso sugere que a satisfação pode estar ligada à estabilidade ou maturidade na carreira.

---

###  Attrition vs. Age (scatterplot com YearsAtCompany)
- Funcionários mais jovens e com pouco tempo de empresa aparecem com maior incidência de **Attrition = Yes**.  
- Já os mais velhos, com muitos anos de casa, tendem a permanecer (Attrition = No).  
- Isso indica que a rotatividade é mais comum entre recém-contratados ou profissionais em início de carreira.

---

###  JobRole vs. Age (boxplot)
- Cargos de liderança (Manager, Director) têm medianas de idade mais altas.  
- Funções técnicas ou de entrada (Technician, Sales Representative) concentram idades mais baixas.  
- Isso reflete o ciclo natural de carreira: cargos de maior responsabilidade são ocupados por profissionais mais experientes.

---

### Attrition vs. Age (histograma com hue)
- A maior parte dos funcionários está entre 25–40 anos.  
- A rotatividade (Attrition = Yes) é mais alta entre os mais jovens, especialmente abaixo dos 30.  
- Funcionários acima dos 40 têm menor probabilidade de sair, mostrando maior retenção nessa faixa.

---

**Resumo dos achados até agora**:
- Rotatividade é maior entre jovens e iniciantes na empresa.  
- Idade média aumenta conforme o cargo é mais sênior.  
- Satisfação no trabalho parece levemente maior em faixas etárias mais altas.  
- A força de trabalho é predominantemente adulta jovem (25–40 anos).  

"""

# Quais grupos têm maior probabilidade de sair da empresa
# Rotatividade (Attrition)

sns.set_theme(style="whitegrid")

# cria 3 gráficos lado a lado
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# 1. Attrition

sns.countplot(
    data=df,
    x="Attrition",
    ax=axes[0]
)

axes[0].set_title("Attrition")

# 2. Age

sns.histplot(
    data=df,
    x="Age",
    hue="Attrition",
    multiple="stack",
    kde=True,
    ax=axes[1]
)

axes[1].set_title("Age vs Attrition")

# 3. Department

sns.countplot(
    data=df,
    x="Department",
    hue="Attrition",
    ax=axes[2]
)

axes[2].set_title("Department vs Attrition")

# gira os nomes do eixo X
axes[2].tick_params(axis='x', rotation=15)

# ajusta espaços automaticamente
plt.tight_layout()

plt.show()

# Salário e benefícios
# Pergunta:Renda influencia satisfação ou saída?

sns.set_theme(style="whitegrid")

# cria a figura
fig, axes = plt.subplots(1, 3, figsize=(20, 5))

# 1. Attrition vs MonthlyIncome

sns.boxplot(
    data=df,
    x="Attrition",
    y="MonthlyIncome",
    ax=axes[0]
)

axes[0].set_title("Salário vs Attrition")

# 2. JobSatisfaction vs MonthlyIncome

sns.boxplot(
    data=df,
    x="JobSatisfaction",
    y="MonthlyIncome",
    ax=axes[1]
)

axes[1].set_title("Satisfação vs Salário")

# 3. Income vs YearsAtCompany

sns.scatterplot(
    data=df,
    x="MonthlyIncome",
    y="YearsAtCompany",
    hue="Attrition",
    ax=axes[2]
)

axes[2].set_title("Tempo de Empresa vs Salário")

# ajusta espaços
plt.tight_layout()

plt.show()

# Treinamento e desenvolvimento
# Analisar se promoções e treinamentos impactam retenção

sns.set_theme(style="whitegrid")

# cria os gráficos lado a lado
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# 1. Promoção vs Attrition

sns.boxplot(
    data=df,
    x="Attrition",
    y="YearsSinceLastPromotion",
    palette="Set2",
    ax=axes[0]
)

axes[0].set_title("Tempo Desde Última Promoção")
axes[0].set_xlabel("Attrition")
axes[0].set_ylabel("Anos")

# 2. Treinamentos vs Attrition

sns.boxplot(
    data=df,
    x="Attrition",
    y="TrainingTimesLastYear",
    palette="pastel",
    ax=axes[1]
)

axes[1].set_title("Treinamentos no Último Ano")
axes[1].set_xlabel("Attrition")
axes[1].set_ylabel("Quantidade")

# ajusta espaçamento
plt.tight_layout()

plt.show()

# Work-Life Balance
# Verificar se equilíbrio vida-trabalho influencia rotatividade.

sns.set_theme(style="whitegrid")

plt.figure(figsize=(8, 5))

sns.countplot(
    data=df,
    x="WorkLifeBalance",
    hue="Attrition",
    palette="Set2"
)

plt.title("Work Life Balance vs Attrition", fontsize=14)
plt.xlabel("Work Life Balance")
plt.ylabel("Quantidade")

plt.tight_layout()
plt.show()

# Performance e envolvimento
# Entender se desempenho e envolvimento afetam retenção.

sns.set_theme(style="whitegrid")

# cria os 3 gráficos lado a lado
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# 1. PerformanceRating

sns.boxplot(
    data=df,
    x="Attrition",
    y="PerformanceRating",
    palette="Set2",
    ax=axes[0]
)

axes[0].set_title("Performance Rating")
axes[0].set_xlabel("Attrition")
axes[0].set_ylabel("Nota")

# 2. JobInvolvement

sns.boxplot(
    data=df,
    x="Attrition",
    y="JobInvolvement",
    palette="pastel",
    ax=axes[1]
)

axes[1].set_title("Job Involvement")
axes[1].set_xlabel("Attrition")
axes[1].set_ylabel("Nível")

# 3. EnvironmentSatisfaction

sns.boxplot(
    data=df,
    x="Attrition",
    y="EnvironmentSatisfaction",
    palette="coolwarm",
    ax=axes[2]
)

axes[2].set_title("Environment Satisfaction")
axes[2].set_xlabel("Attrition")
axes[2].set_ylabel("Satisfação")

# ajusta espaçamento
plt.tight_layout()

plt.show()

# Boxplot – Attrition vs DistanceFromHome
# Eixo X (Attrition): separa quem saiu da empresa (Yes) e quem ficou (No).
# Eixo Y (DistanceFromHome): mostra a distância da casa até o trabalho.

plt.figure(figsize=(12,6))
sns.boxplot(data=df, x="Attrition", y="DistanceFromHome")
plt.title("Attrition vs DistanceFromHome")
plt.show()

# Scatterplot – DistanceFromHome vs MonthlyIncome (Attrition)
# Eixo X (DistanceFromHome): distância da casa até o trabalho.
# Eixo Y (MonthlyIncome): salário mensal.

plt.figure(figsize=(12,6))
sns.scatterplot(data=df, x="DistanceFromHome", y="MonthlyIncome", hue="Attrition")
plt.title("DistanceFromHome vs MonthlyIncome (Attrition)")
plt.show()

"""### 1. **Attrition (Rotatividade)**
- A maioria dos funcionários permanece, mas há cerca de 200 casos de saída.  
- A saída é mais comum entre **funcionários jovens (30–35 anos)** e em alguns departamentos específicos, como **Sales**.  
- Rotatividade concentrada em início de carreira e áreas comerciais.

---

### 2. **Salário e benefícios**
- Funcionários que ficaram (`No`) têm **salários medianos mais altos** e maior variação de renda.  
- A satisfação no trabalho não varia muito com salário, mas quem ganha mais tende a permanecer.  
- Funcionários com **longa permanência e salários altos** quase não apresentam rotatividade.  
- Salário e tempo de empresa são fatores de retenção.

---

### 3. **Treinamento e desenvolvimento**
- Tempo desde a última promoção: quem saiu (`Yes`) tem mediana menor (cerca de 1 ano), enquanto quem ficou tem mediana maior (~2 anos).  
- Treinamentos no último ano: distribuição semelhante entre os grupos, sem grande impacto direto.  
- Promoções parecem ter mais influência na retenção do que treinamentos.

---

### 4. **Work-Life Balance**
- Funcionários com equilíbrio **nível 3** são maioria e têm menor rotatividade.  
- Níveis mais baixos (1 e 2) apresentam proporção maior de saída.  
- Equilíbrio vida-trabalho é um fator importante para retenção.

---

### 5. **Performance e envolvimento**
- Performance Rating não mostra diferença significativa entre quem saiu e quem ficou.  
- Job Involvement e Environment Satisfaction também têm distribuições semelhantes, mas níveis mais baixos aparecem com maior proporção de saída.  
- Desempenho não explica a saída, mas envolvimento e satisfação ambiental podem contribuir.

---

### 6. **Perfil demográfico**
- Funcionários que moram mais longe têm maior rotatividade (boxplot de DistanceFromHome).  
- Estado civil e gênero podem ser explorados, mas geralmente não são os principais fatores.  
- Distância da casa até o trabalho é um fator relevante para explicar saída.

---

 **Resumo geral da análise exploratória (EDA):**
- **Rotatividade maior entre jovens, cargos de entrada e áreas comerciais.**  
- **Salário e tempo de empresa são fortes fatores de retenção.**  
- **Promoções e equilíbrio vida-trabalho influenciam saída.**  
- **Distância da casa até o trabalho aumenta probabilidade de rotatividade.**  
- **Desempenho não é determinante, mas satisfação e envolvimento ajudam.**

Let's identify columns that can be eliminated due to having constant values or being unique identifiers.
"""

# estilo visual
sns.set_theme(style="white")

# figura maior
plt.figure(figsize=(14, 10))

# copia do dataframe
df_temp = df.copy()

# remove colunas irrelevantes ou constantes
df_temp = df_temp.drop(columns=[
    "EmployeeCount", "StandardHours", "EmployeeNumber", "Over18",
    "DailyRate", "HourlyRate", "MonthlyRate"  # redundantes de MonthlyIncome
])

# transforma Attrition em numérico
df_temp["Attrition"] = df_temp["Attrition"].map({
    "Yes": 1,
    "No": 0
})

# matriz de correlação
corr = df_temp.corr(numeric_only=True)

# heatmap melhorado
sns.heatmap(
    corr,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    linewidths=0.5,
    square=True,
    cbar_kws={"shrink": 0.8},
    annot_kws={"size": 8}
)

# título
plt.title("Matriz de Correlação", fontsize=18)

# melhora labels
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)

# ajusta layout
plt.tight_layout()

plt.show()

# copia do dataframe
df_temp = df.copy()

# remove colunas irrelevantes ou constantes
df_temp = df_temp.drop(columns=[
    "EmployeeCount",
    "StandardHours",
    "EmployeeNumber",
    "Over18",
    "DailyRate",
    "HourlyRate",
    "MonthlyRate",
    "YearsInCurrentRole",
    "YearsWithCurrManager",
    "JobLevel"
])

# transforma Attrition em numérico
df_temp["Attrition"] = df_temp["Attrition"].map({"Yes": 1, "No": 0})

# matriz de correlação
corr = df_temp.corr(numeric_only=True)

# estilo visual
sns.set_theme(style="white")

# figura maior
plt.figure(figsize=(14, 10))

# heatmap
sns.heatmap(
    corr,
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    linewidths=0.5,
    square=True,
    cbar_kws={"shrink": 0.8},
    annot_kws={"size": 8}
)

# título
plt.title("Matriz de Correlação - Colunas Enxutas", fontsize=18)

# labels
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)

# layout
plt.tight_layout()
plt.show()

# Cópia do dataset

df_model = df.copy()

# Removendo colunas desnecessárias

df_model = df_model.drop(columns=[
    "EmployeeCount",
    "StandardHours",
    "EmployeeNumber",
    "Over18",
    "DailyRate",
    "HourlyRate",
    "MonthlyRate",
    "YearsInCurrentRole",
    "YearsWithCurrManager",
    "JobLevel"
])

# Target (Attrition)

df_model["Attrition"] = df_model["Attrition"].map({
    "Yes": 1,
    "No": 0
})

# Encoding das variáveis categóricas

df_model = pd.get_dummies(
    df_model,
    drop_first=True
)

# Verificando dataset final

print(df_model.shape)

display(df_model.head())

# salva dataset pronto para modelagem

df_model.to_csv(
    "hr_attrition_processed.csv",
    index=False
)

print("Dataset salvo com sucesso.")

df_model.to_csv("hr_attrition_processed.csv", index=False)