# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QP1IERSVpVoSHywh76dm7nFZ2bNzthhn
"""

# app.py

import pickle
import pandas as pd
import streamlit as st

# =========================================
# LOAD MODELO
# =========================================

with open("ensemble_attrition_model.pkl", "rb") as file:
    model = pickle.load(file)

with open("model_columns.pkl", "rb") as file:
    model_columns = pickle.load(file)

# =========================================
# PAGE CONFIG
# =========================================

st.set_page_config(
    page_title="Employee Attrition Prediction",
    layout="centered"
)

st.title("Employee Attrition Prediction")

st.write(
    """
    Aplicação de Machine Learning para prever
    risco de saída de funcionários.
    """
)

# =========================================
# INPUTS
# =========================================

age = st.slider("Age", 18, 60, 30)

monthly_income = st.number_input(
    "Monthly Income",
    min_value=1000,
    max_value=50000,
    value=5000
)

distance_from_home = st.slider(
    "Distance From Home",
    1,
    30,
    5
)

job_satisfaction = st.slider(
    "Job Satisfaction",
    1,
    4,
    3
)

environment_satisfaction = st.slider(
    "Environment Satisfaction",
    1,
    4,
    3
)

work_life_balance = st.slider(
    "Work Life Balance",
    1,
    4,
    3
)

total_working_years = st.slider(
    "Total Working Years",
    0,
    40,
    10
)

years_at_company = st.slider(
    "Years At Company",
    0,
    40,
    5
)

overtime = st.selectbox(
    "OverTime",
    ["No", "Yes"]
)

stock_option_level = st.slider(
    "Stock Option Level",
    0,
    3,
    1
)

# =========================================
# PREDICTION
# =========================================

if st.button("Predict Attrition"):

    input_data = {
        "Age": age,
        "MonthlyIncome": monthly_income,
        "DistanceFromHome": distance_from_home,
        "JobSatisfaction": job_satisfaction,
        "EnvironmentSatisfaction": environment_satisfaction,
        "WorkLifeBalance": work_life_balance,
        "TotalWorkingYears": total_working_years,
        "YearsAtCompany": years_at_company,
        "StockOptionLevel": stock_option_level,
        "OverTime_Yes": 1 if overtime == "Yes" else 0
    }

    # cria dataframe
    input_df = pd.DataFrame([input_data])

    # garante mesmas colunas do treino
    input_df = input_df.reindex(
        columns=model_columns,
        fill_value=0
    )

    # previsão
    prediction = model.predict(input_df)[0]

    probability = model.predict_proba(
        input_df
    )[0][1]

    # resultado
    st.subheader("Prediction Result")

    if prediction == 1:
        st.error(
            f"High Risk of Attrition ({probability:.2%})"
        )
    else:
        st.success(
            f"Low Risk of Attrition ({probability:.2%})"
        )