# -*- coding: utf-8 -*-
"""predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cgUyrw_Sp9Nubc8GNDLjb3ox-I9-7efg
"""

#  Importar bibliotecas
import pandas as pd
import pickle

# Carregar modelo

with open("ensemble_attrition_model.pkl", "rb") as file:
    model = pickle.load(file)

# Carregar colunas

with open("model_columns.pkl", "rb") as file:
    model_columns = pickle.load(file)

# Criar novo funcionário
# exemplo

novo_funcionario = {
    "Age": 35,
    "DistanceFromHome": 10,
    "EnvironmentSatisfaction": 2,
    "JobSatisfaction": 2,
    "MonthlyIncome": 4000,
    "OverTime_Yes": 1,
    ...
}

'''Forma profissional

Usar DataFrame: '''

novo_df = pd.DataFrame(
    [novo_funcionario]
)

# Garantir mesma ordem das colunas

novo_df = novo_df.reindex(
    columns=model_columns,
    fill_value=0
)

# Fazer previsão

predicao = model.predict(novo_df)
probabilidade = model.predict_proba(novo_df)[:,1]

# Resultado

print("Previsão:", predicao[0])

print("Probabilidade de saída:", probabilidade[0])

"""| Resultado | Significado           |
| --------- | --------------------- |
| `0`       | funcionário permanece |
| `1`       | risco de saída        |

"""

''' Melhor ainda

Você pode converter:'''

if predicao[0] == 1:
    print("Funcionário com risco de saída")
else:
    print("Funcionário com baixa probabilidade de saída")