# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mDYzGfSoOnQ0tWlLaLQacNBepGu53MeW
"""

# =========================================
# IMPORTAÇÃO DAS BIBLIOTECAS
# =========================================

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

print("Bibliotecas importadas com sucesso.")

df = pd.read_csv("hr_attrition_processed.csv")

df.head()

# FEATURES E TARGET

X = df.drop("Attrition", axis=1)

y = df["Attrition"]

# TRAIN TEST SPLIT

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Treino:", X_train.shape)
print("Teste :", X_test.shape)

# MODELO

rf_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    random_state=42
)

# TREINAMENTO

rf_model.fit(X_train, y_train)

print("Modelo treinado com sucesso.")

# PREVISÕES

y_pred = rf_model.predict(X_test)
y_prob = rf_model.predict_proba(X_test)[:, 1]

# MÉTRICAS

print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1-Score :", f1_score(y_test, y_pred))
print("ROC-AUC  :", roc_auc_score(y_test, y_prob))

# MATRIZ DE CONFUSÃO

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues"
)

plt.title("Matriz de Confusão")
plt.xlabel("Predito")
plt.ylabel("Real")
plt.show()

"""Meu modelo está com um comportamento MUITO comum em datasets desbalanceados.

Oque aconteceu em tese? este dataset tem muito mais No Attrition do que Yes Attrition,o modelo aprendeu a prever quase tudo como 0
por isso:

Accuracy ficou alta (83%)
mas Recall ficou péssimo (8%)

Na prática:

ele quase não detecta quem vai sair da empresa.  
Sua matriz mostra isso claramente:

Real	Predito	Quantidade  
0 → 0	Verdadeiro Negativo	242  
0 → 1	Falso Positivo	5  
1 → 0	Falso Negativo	43  
1 → 1	Verdadeiro Positivo	4

# aplicar o smote no dataset

Serve para gerar exemplos sintéticos da classe minoritária. Isso equilibra as classes e ajuda o modelo a aprender padrões da classe “Yes” sem simplesmente duplicar registros.
"""

from imblearn.over_sampling import SMOTE

# SMOTE

smote = SMOTE(
    random_state=42
)

X_train_smote, y_train_smote = smote.fit_resample(
    X_train,
    y_train
)

print("Antes:", y_train.value_counts())

print("Depois:", y_train_smote.value_counts())

# MODELO

rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=12,
    random_state=42
)

# TREINAMENTO

rf_model.fit(
    X_train_smote,
    y_train_smote
)

print("Modelo treinado.")

# previsões

y_pred = rf_model.predict(X_test)
y_prob = rf_model.predict_proba(X_test)[:, 1]

print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1-Score :", f1_score(y_test, y_pred))
print("ROC-AUC  :", roc_auc_score(y_test, y_prob))

"""O dataset era desbalanceado, então o modelo inicialmente apresentava alta accuracy, mas recall muito baixo, identificando poucos funcionários com risco de saída.

Para resolver isso, apliquei SMOTE para balanceamento das classes.

Após o balanceamento, o recall aumentou significativamente, melhorando a capacidade do modelo em detectar colaboradores com maior probabilidade de attrition.
"""

importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf_model.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

importance.head(10)

plt.figure(figsize=(10,6))

sns.barplot(
    data=importance.head(10),
    x="Importance",
    y="Feature"
)

plt.title("Top 10 Features Mais Importantes")

plt.show()

from sklearn.ensemble import RandomForestClassifier

# RANDOM FOREST BALANCEADO

rf_balanced = RandomForestClassifier(
    n_estimators=300,
    max_depth=12,
    class_weight="balanced",
    random_state=42
)

# treino
rf_balanced.fit(
    X_train,
    y_train
)

print("Modelo treinado.")

# previsões

y_pred_bal = rf_balanced.predict(X_test)
y_prob_bal = rf_balanced.predict_proba(X_test)[:, 1]

# Avaliação
print("Accuracy :", accuracy_score(y_test, y_pred_bal))
print("Precision:", precision_score(y_test, y_pred_bal))
print("Recall   :", recall_score(y_test, y_pred_bal))
print("F1-Score :", f1_score(y_test, y_pred_bal))
print("ROC-AUC  :", roc_auc_score(y_test, y_prob_bal))

y_pred_threshold = (y_prob_bal >= 0.3).astype(int)

# comparação dos modelos

comparacao = pd.DataFrame({
    "Modelo": [
        "Random Forest Original",
        "Random Forest + SMOTE",
        "RF + class_weight",
        "RF + Threshold 0.3"
    ],

    "Accuracy": [
        0.8367,
        0.8435,
        accuracy_score(y_test, y_pred_bal),
        accuracy_score(y_test, y_pred_threshold)
    ],

    "Precision": [
        0.4444,
        0.5172,
        precision_score(y_test, y_pred_bal),
        precision_score(y_test, y_pred_threshold)
    ],

    "Recall": [
        0.0851,
        0.3191,
        recall_score(y_test, y_pred_bal),
        recall_score(y_test, y_pred_threshold)
    ],

    "F1-Score": [
        0.1428,
        0.3947,
        f1_score(y_test, y_pred_bal),
        f1_score(y_test, y_pred_threshold)
    ],

    "ROC-AUC": [
        0.8151,
        0.7418,
        roc_auc_score(y_test, y_prob_bal),
        roc_auc_score(y_test, y_prob_bal)
    ]
})

comparacao

# novo threshold

threshold = 0.3

y_pred_threshold = (
    y_prob_bal >= threshold
).astype(int)

# avaliação com novo threshold
print("Accuracy :", accuracy_score(y_test, y_pred_threshold))
print("Precision:", precision_score(y_test, y_pred_threshold))
print("Recall   :", recall_score(y_test, y_pred_threshold))
print("F1-Score :", f1_score(y_test, y_pred_threshold))
print("ROC-AUC  :", roc_auc_score(y_test, y_prob_bal))

cm = confusion_matrix(
    y_test,
    y_pred_threshold
)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues"
)

plt.title(
    f"Matriz de Confusão - Threshold {threshold}"
)

plt.xlabel("Predito")
plt.ylabel("Real")
plt.show()

from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

# Separar features e target
X = df.drop("Attrition", axis=1)
y = df["Attrition"]

# Dividir em treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

# Aplicar SMOTE no treino
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

# Treinar modelo com class_weight="balanced"
model = LogisticRegression(max_iter=1000, class_weight="balanced")
model.fit(X_train_res, y_train_res)

# Avaliar
y_pred = model.predict(X_test)
print("Matriz de Confusão:\n", confusion_matrix(y_test, y_pred))
print("\nRelatório de Classificação:\n", classification_report(y_test, y_pred))

from xgboost import XGBClassifier

# MODELO XGBOOST

xgb_model = XGBClassifier(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric="logloss"
)

# treino
xgb_model.fit(
    X_train_res,
    y_train_res
)

print("XGBoost treinado.")

"""Eu configurei e treinei um **modelo XGBoost** para prever a saída de funcionários.  

 **Escolhi o algoritmo XGBoost** porque ele é poderoso para lidar com dados complexos e desbalanceados.  
- **Defini os parâmetros principais**:
  - `n_estimators=300`: pedi para o modelo construir 300 árvores, aumentando a capacidade de aprender padrões.  
  - `max_depth=5`: limitei a profundidade das árvores para evitar overfitting.  
  - `learning_rate=0.05`: defini uma taxa de aprendizado baixa, para que o modelo aprenda de forma mais gradual e estável.  
  - `subsample=0.8`: usei 80% dos dados em cada árvore, introduzindo aleatoriedade e robustez.  
  - `colsample_bytree=0.8`: usei 80% das variáveis em cada árvore, para aumentar a diversidade.  
  - `random_state=42`: garanti reprodutibilidade.  
  - `eval_metric="logloss"`: escolhi logloss como métrica de avaliação durante o treino, adequada para classificação binária.  

- **Treinei o modelo (`fit`)** usando os dados balanceados pelo SMOTE (`X_train_res`, `y_train_res`).  
- Com isso, o modelo aprendeu em um cenário mais equilibrado entre “Yes” e “No Attrition”, o que deve melhorar o recall da classe minoritária.  
"""

# previsões

y_pred_xgb = xgb_model.predict(X_test)
y_prob_xgb = xgb_model.predict_proba(X_test)[:, 1]

# avaliação com xgb

print("Accuracy :", accuracy_score(y_test, y_pred_xgb))
print("Precision:", precision_score(y_test, y_pred_xgb))
print("Recall   :", recall_score(y_test, y_pred_xgb))
print("F1-Score :", f1_score(y_test, y_pred_xgb))
print("ROC-AUC  :", roc_auc_score(y_test, y_prob_xgb))

cm = confusion_matrix(
    y_test,
    y_pred_xgb
)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues"
)

plt.title("XGBoost - Matriz de Confusão")
plt.xlabel("Predito")
plt.ylabel("Real")

plt.show()

# =========================================
# NOVO THRESHOLD
# =========================================

threshold = 0.3

y_pred_xgb_threshold = (
    y_prob_xgb >= threshold
).astype(int)

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

print("Accuracy :", accuracy_score(y_test, y_pred_xgb_threshold))

print("Precision:", precision_score(y_test, y_pred_xgb_threshold))

print("Recall   :", recall_score(y_test, y_pred_xgb_threshold))

print("F1-Score :", f1_score(y_test, y_pred_xgb_threshold))

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(
    y_test,
    y_pred_xgb_threshold
)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues"
)

plt.title(
    f"XGBoost - Threshold {threshold}"
)

plt.xlabel("Predito")

plt.ylabel("Real")

plt.show()

from sklearn.metrics import roc_curve, auc

# =========================================
# ROC CURVE
# =========================================

fpr, tpr, thresholds = roc_curve(
    y_test,
    y_prob_xgb
)

roc_auc = auc(fpr, tpr)

# plot
plt.figure(figsize=(8,6))

plt.plot(
    fpr,
    tpr,
    label=f"AUC = {roc_auc:.2f}"
)

plt.plot(
    [0,1],
    [0,1],
    linestyle="--"
)

plt.xlabel("False Positive Rate")

plt.ylabel("True Positive Rate")

plt.title("ROC Curve - XGBoost")

plt.legend()

plt.show()

from sklearn.metrics import (
    precision_recall_curve,
    average_precision_score
)

# =========================================
# PRECISION RECALL CURVE
# =========================================

precision, recall, thresholds = precision_recall_curve(
    y_test,
    y_prob_xgb
)

ap_score = average_precision_score(
    y_test,
    y_prob_xgb
)

# plot
plt.figure(figsize=(8,6))

plt.plot(
    recall,
    precision,
    label=f"AP = {ap_score:.2f}"
)

plt.xlabel("Recall")

plt.ylabel("Precision")

plt.title("Precision-Recall Curve - XGBoost")

plt.legend()

plt.grid(True)

plt.show()

# CALCULAR F1 PARA CADA THRESHOLD

f1_scores = (
    2 * (precision * recall)
) / (precision + recall + 1e-10)

# melhor índice
best_idx = np.argmax(f1_scores)

# melhor threshold
best_threshold = thresholds[best_idx]

print("Melhor Threshold:", best_threshold)

print("Melhor F1:", f1_scores[best_idx])

print("Precision:", precision[best_idx])

print("Recall:", recall[best_idx])

# =========================================
# NOVAS PREVISÕES
# =========================================

y_pred_best = (
    y_prob_xgb >= best_threshold
).astype(int)

print("Accuracy :", accuracy_score(y_test, y_pred_best))

print("Precision:", precision_score(y_test, y_pred_best))

print("Recall   :", recall_score(y_test, y_pred_best))

print("F1-Score :", f1_score(y_test, y_pred_best))

"""Em resumo:
fui implementar um método objetivo para encontrar o threshold que maximiza o F1-score, e com isso consegui aumentar recall para mais de 50%, tornando o modelo muito mais aplicável na prática.

Os próximo passo, exploarar a importância das variáveis.

scale_pos_weight no XGBoost  
hyperparameter tuning  
feature engineering  
ensembles.    


```
# Isto está formatado como código
```

scale_pos_weight no XGBoost é um hiperparâmetro usado para lidar com conjuntos de dados de classificação binária desbalanceados (quando você tem muito mais exemplos de uma classe do que de outra)

# Como funciona?

Ele atribui um peso maior aos erros cometidos na classe positiva (geralmente a classe minoritária, como "fraude" ou "doença"). Isso força o modelo a prestar mais atenção nela, em vez de focar apenas na classe majoritária para obter uma acurácia alta, mas inútil.

# O que acontece na prática?

Aumenta o Recall: O modelo fica melhor em encontrar os casos positivos.Diminui a Precisão: Pode haver um aumento de "falsos positivos".Probabilidades: As probabilidades previstas podem ficar descalibradas (não refletindo a probabilidade real, mas sim a importância ajustada)
"""

# scaçe pos weight

scale_pos_weight = (
    y_train.value_counts()[0]
    /
    y_train.value_counts()[1]
)

print(scale_pos_weight)

# XGBOOST BALANCEADO

xgb_balanced = XGBClassifier(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,

    scale_pos_weight=scale_pos_weight,

    random_state=42,
    eval_metric="logloss"
)

# treino
xgb_balanced.fit(
    X_train,
    y_train
)

print("Modelo treinado.")

# previsões

y_pred_bal = xgb_balanced.predict(X_test)
y_prob_bal = xgb_balanced.predict_proba(X_test)[:, 1]

# metricas

print("Accuracy :", accuracy_score(y_test, y_pred_bal))
print("Precision:", precision_score(y_test, y_pred_bal))
print("Recall   :", recall_score(y_test, y_pred_bal))
print("F1-Score :", f1_score(y_test, y_pred_bal))
print("ROC-AUC  :", roc_auc_score(y_test, y_prob_bal))

from sklearn.model_selection import RandomizedSearchCV

param_grid = {
    "max_depth": [3, 4, 5, 6],
    "learning_rate": [0.01, 0.05, 0.1],
    "n_estimators": [100, 200, 300],
    "subsample": [0.7, 0.8, 1.0],
    "colsample_bytree": [0.7, 0.8, 1.0]
}

random_search = RandomizedSearchCV(
    estimator=xgb_balanced,

    param_distributions=param_grid,

    n_iter=20,

    scoring="f1",

    cv=3,

    verbose=1,

    random_state=42,

    n_jobs=-1
)

random_search.fit(
    X_train,
    y_train
)

print(random_search.best_params_)

best_model = random_search.best_estimator_

df["IncomePerYear"] = (
    df["MonthlyIncome"] * 12
)

df["IncomeExperienceRatio"] = (
    df["MonthlyIncome"]
    /
    (df["TotalWorkingYears"] + 1)
)

df["PromotionDelay"] = (
    df["YearsAtCompany"]
    -
    df["YearsSinceLastPromotion"]
)

df["OverallSatisfaction"] = (
    df["JobSatisfaction"]
    +
    df["EnvironmentSatisfaction"]
    +
    df["RelationshipSatisfaction"]
    +
    df["WorkLifeBalance"]
) / 4

#  Ensembles
''' Voting Classifier

Combina:

Logistic Regression
Random Forest
XGBoost.'''

from sklearn.ensemble import VotingClassifier

from sklearn.ensemble import VotingClassifier

# =========================================
# ENSEMBLE
# =========================================

ensemble = VotingClassifier(
    estimators=[
        ("lr", model),
        ("rf", rf_model),
        ("xgb", xgb_balanced)
    ],

    voting="soft"
)

ensemble.fit(X_train, y_train)

y_pred_ensemble = ensemble.predict(X_test)
y_prob_ensemble = ensemble.predict_proba(X_test)[:, 1]

# metricas

print("Accuracy :", accuracy_score(y_test, y_pred_ensemble))
print("Precision:", precision_score(y_test, y_pred_ensemble))
print("Recall   :", recall_score(y_test, y_pred_ensemble))
print("F1-Score :", f1_score(y_test, y_pred_ensemble))
print("ROC-AUC  :", roc_auc_score(y_test, y_prob_ensemble))

"""O ensemble:

ficou mais preciso  
reduziu falsos positivos   
melhorou separação das classes  
aumentou F1-score   
aumentou ROC-AUC.  
"""



"""# Qual modelo escolher?
Se o objetivo for:  
detectar o máximo possível de saídas   

→ XGBoost com threshold tuning.

# Se o objetivo for:
equilíbrio geral e menos alarmes falsos

→ Ensemble.

Porque:

melhor F1 e ROC-AUC
"""

import pickle

with open("xgboost_attrition_model.pkl", "wb") as file:
    pickle.dump(xgb_balanced, file)

print("XGBoost salvo com sucesso.")

with open("ensemble_attrition_model.pkl", "wb") as file:
    pickle.dump(ensemble, file)

print("Ensemble salvo com sucesso.")

model_columns = X.columns.tolist()

with open("model_columns.pkl", "wb") as file:
    pickle.dump(model_columns, file)

print("Colunas salvas.")

with open("model_columns.pkl", "rb") as file:
    model_columns = pickle.load(file)

